// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_nYoX4ckf1ZFDXN8MFEtOCS_MR4tyOAM',
    appId: '1:636391104941:web:d288994195d93e4f274124',
    messagingSenderId: '636391104941',
    projectId: 'homework4-79bf5',
    authDomain: 'homework4-79bf5.firebaseapp.com',
    storageBucket: 'homework4-79bf5.firebasestorage.app',
    measurementId: 'G-3WYJ7VNSCH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-giqWHkQ0sWrNNA0dmCXkTKU41913IqU',
    appId: '1:636391104941:android:f288c51d0b400323274124',
    messagingSenderId: '636391104941',
    projectId: 'homework4-79bf5',
    storageBucket: 'homework4-79bf5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqaPuPr30DaamQEX4aAnDUXOsYxpmX8LA',
    appId: '1:636391104941:ios:e1d09e5188627d2d274124',
    messagingSenderId: '636391104941',
    projectId: 'homework4-79bf5',
    storageBucket: 'homework4-79bf5.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication24',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqaPuPr30DaamQEX4aAnDUXOsYxpmX8LA',
    appId: '1:636391104941:ios:e1d09e5188627d2d274124',
    messagingSenderId: '636391104941',
    projectId: 'homework4-79bf5',
    storageBucket: 'homework4-79bf5.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication24',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_nYoX4ckf1ZFDXN8MFEtOCS_MR4tyOAM',
    appId: '1:636391104941:web:247a02518a923241274124',
    messagingSenderId: '636391104941',
    projectId: 'homework4-79bf5',
    authDomain: 'homework4-79bf5.firebaseapp.com',
    storageBucket: 'homework4-79bf5.firebasestorage.app',
    measurementId: 'G-P6B9VKQ1HT',
  );
}
